version: '3.8'

services:
  # MongoDB服务
  mongo:
    image: mongo:latest
    container_name: todo-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  # 后端API服务
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: todo-api
    restart: always
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - mongo
    networks:
      - todo-app-network
    environment:
      - PORT=${API_PORT}
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DATABASE}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - NODE_ENV=${NODE_ENV}

  # 前端应用服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_URL=http://localhost:${API_PORT}
    container_name: todo-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - api
    networks:
      - todo-app-network

networks:
  todo-app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
