version: '3.8'

services:
  # MongoDB服务
  mongo:
    image: mongo:latest
    container_name: todo-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  # 后端API服务
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: todo-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - todo-app-network
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://admin:password@mongo:27017/todo-app?authSource=admin
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRE=30d
      - NODE_ENV=production

  # 前端应用服务
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: todo-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - todo-app-network

networks:
  todo-app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
